# SETTINGS
app:
  external-url: http://localhost:8080
  password-token-expiration-hours: 2

#GENERAL
spring:
  application.name: hospital

#DATA SOURCE
  datasource:
    hikari.pool-name: hospital
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://127.0.0.1:5432/hospital
    username: postgres
    password: postgres

#JPA
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: true
    properties:
      hibernate.dialect: hospital.infrastructure.hibernate.PostgreSQLDialect
      hibernate.default_schema: public

